### ISSUE TITLE
Not written in typescript

### ISSUE THREAD

**Issue by KegenGuyll** [Smarticles101/idk-dating#1]
### Why You Should Use TypeScript?

- TypeScript simplifies JavaScript code, making it easier to read and debug.
- TypeScript is open source.
- TypeScript provides highly productive development tools for JavaScript IDEs and practices, like static checking.
- TypeScript makes code easier to read and understand.
- With TypeScript, we can make a huge improvement over plain JavaScript.
- TypeScript gives us all the benefits of ES6 (ECMAScript 6), plus more productivity.
- TypeScript can help us to avoid painful bugs that developers commonly run into when writing JavaScript by type checking the code.
- Powerful type system, including generics.
- TypeScript is nothing but JavaScript with some additional features.
- Structural, rather than nominal.
- TypeScript code can be compiled as per ES5 and ES6 standards to support the latest browser.
- Aligned with ECMAScript for compatibility.
- Starts and ends with JavaScript.
- Supports static typing.
- TypeScript will save developers time.
- TypeScript is a superset of ES3, ES5, and ES6.

**Comment by Smarticles101** [comment]
What the frick Kegan you already know my feelings towards typescript

**Comment by KegenGuyll** [comment]
typescript is the future, your living in like 2012

**Comment by KegenGuyll** [comment]
I think you should rethink this
